### PR TITLE
CMS App Production Ver.

### PR DESCRIPTION
**Pull request by MoyasiGinko**
### In this milestone,
- Created a branches
- Implemented features like:
- - Creating categories
- - Creating new transactions
- - CRUD implementation 
- Added a dashboard
- Added a welcome page
- Implemented authentication using devise
- Added stylings for the app
- Implemented integration testing.
- Deployed the production unit on `render.com`
- Added a presentation video of the app in the readme.

Note: New presentation video link [Presentation Video](https://www.loom.com/share/953693b5858e4f4192ddcb6f74b67f2e?sid=a83079f3-6f66-4652-8c04-19fa2e0d99e0)
Thank you, Happy Coding 👋

### CODE REVIEW

**Review by Qoosim — COMMENTED** [review]
#  *Status: Invalid Request* :red_circle: 

Hi @MoyasiGinko, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.



## Invalid Code Review Request

You have submitted a project, that has wrong workflow. You're expected to follow [Gitflow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md) which means you're supposed to open your PR from `feature-branch` into the `development` branch not from `development` branch into the `main` branch

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by bienvenuushindi — CHANGES_REQUESTED** [review]
Hi @MoyasiGinko  , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
May I highlight the following:

- The repo looks professional.:heavy_check_mark:
- There are no linter errors:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:
- Your project looks good:heavy_check_mark:
- Kudos for the extra work (Recent Activity section, Edit and Delete a transaction,etc) :+1: :clap: 
- great job on your exceptional work :heavy_check_mark: :clap:  :fire:

## Required Changes ♻️
I wanted to take a moment to congratulate you on the outstanding work you've done on this project. I must say, I'm truly impressed by the remarkable progress you've made so far. My requested change appears to be a relatively minor aspect compared to the significant accomplishments you've achieved in this project. Please keep in mind that even though this change might seem less significant in comparison, it's an important part of ensuring the project's completeness and integrity
:arrow_down: :point_down: 
While your presentation was informative and well-executed :clap: :+1: , there is one :pinched_fingers:  specific aspect we'd like to include :heavy_plus_sign: to make it more engaging :zap:  and insightful :bulb: .
Screenshot from 2023-09-21 23-14-44


Could you please :pray:  record :record_button: a short supplementary video clip :film_projector:  where you present a piece of code :man_technologist:  from your project that you find particularly interesting or are proud of creating? This will add a valuable dimension to your presentation by allowing viewers to see a specific example of your work and hear your insights :bulb:  about it.

Please :pray:  keep this supplementary video brief, focusing on the code snippet and your thoughts on it. Once you have the clip ready, **kindly Add the link under the Pull Request Summary** 

## Optional suggestions

_Check the comments under the review._

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by MoyasiGinko** [comment]
Note: New presentation video link [Presentation Video](https://www.loom.com/share/953693b5858e4f4192ddcb6f74b67f2e?sid=a83079f3-6f66-4652-8c04-19fa2e0d99e0)

**Review by Whoistolu — APPROVED** [review]
### Hi @MoyasiGinko 

Great job implementing the recommended fix by the previous reviewer 👍🏽 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

# STATUS: APPROVED 🟢
**Congratulations! 🎉** 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
